"""
Seed: add 16 new illustrative example verticals to the examples collection.

Run once:  python3 /app/migrations/seed_new_examples.py
Idempotent: upserts by slug.

All entries are ILLUSTRATIVE — no quotes, no names, no locations, no invented
numbers. results[] carry mechanisms only.
"""
import asyncio, os, uuid
from datetime import datetime, timezone
from pathlib import Path
from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env")
client = AsyncIOMotorClient(os.environ["MONGO_URL"])
db = client[os.environ["DB_NAME"]]

EXAMPLES = [   {   'slug': 'event-production',
        'icon': '🎪',
        'industry': 'Event Production & Experiential',
        'size': 'Office team + freelance crew',
        'color': 'pink',
        'tagline': 'Quotes re-typed into job sheets, into WhatsApp, into stock orders. Five copies of the '
                   'truth, and only some get updated.',
        'before': [   'Concept images made by hand per pitch',
                      'Job details re-typed at every stage',
                      'Crew briefed in a WhatsApp thread that scrolls',
                      'Kit clashes found on load-out day',
                      'Stock ordered when someone remembers'],
        'integrated': [   'Approve a quote and the job pack builds itself',
                          'Order-by dates worked backwards from load-out',
                          'Kit committed elsewhere flagged the moment it clashes',
                          'Crew brief at a link: role, call time, site access',
                          'Venue library: bay hours, lift sizes, parking, permits'],
        'ai': [   'Concept visuals generated from the client brief, before samples',
                  'Stock volumes estimated from the accepted spec',
                  'Site issues photographed and routed to the right person',
                  'Post-event debrief written from what actually happened'],
        'results': [   {'k': 'Source of truth', 'v': 'The quote'},
                       {'k': 'Ordering', 'v': 'Backwards from load-out'},
                       {'k': 'Crew brief', 'v': 'A link, not a thread'}],
        'quote': '',
        'quoteBy': '',
        'category': 'community',
        'published': True},
    {   'slug': 'marquee-hire',
        'icon': '⛺',
        'industry': 'Marquee & Event Hire',
        'size': 'Family firm · seasonal crew',
        'color': 'mint',
        'tagline': 'Every booking depends on ground conditions and weather nobody can see yet, and three '
                   'weddings want the same flooring.',
        'before': [   'Availability held in a wall planner',
                      'Site visits for every enquiry',
                      'Weather contingency agreed by phone',
                      'Furniture counts reconciled by hand',
                      'Deposits chased manually'],
        'integrated': [   'Live availability by structure, flooring and furniture',
                          'Photo-and-measurement site survey from the customer',
                          'Weather contingency priced into the quote from the start',
                          'Load lists per van, per site, per day',
                          'Deposits taken online at booking'],
        'ai': [   "Layout visualised on the customer's own field or garden photo",
                  'Capacity and furniture counts from guest numbers',
                  'Ground condition risk flagged from forecast and site notes',
                  'Off-season enquiry follow-ups drafted automatically'],
        'results': [   {'k': 'Visualised on', 'v': 'Their own site photo'},
                       {'k': 'Clash detection', 'v': 'Across the season'},
                       {'k': 'Deposits', 'v': 'Taken at booking'}],
        'quote': '',
        'quoteBy': '',
        'category': 'community',
        'published': True},
    {   'slug': 'exhibition-stands',
        'icon': '🏗️',
        'industry': 'Exhibition & Stand Builders',
        'size': 'Studio + build crew',
        'color': 'blue',
        'tagline': 'Build and breakdown windows are fixed, fined if missed, and every venue has its own '
                   'paperwork.',
        'before': [   'Visuals produced per pitch, mostly unpaid',
                      'Venue rules re-read from PDFs each time',
                      'Health and safety documents emailed late',
                      'Shipping deadlines tracked in a spreadsheet',
                      'Client sign-off chased over email'],
        'integrated': [   'Client approves visuals and revisions in one place',
                          'Venue record holds rules, windows and paperwork',
                          'Build and break schedules generated from the show dates',
                          'Freight and print deadlines calculated backwards',
                          'Sign-off recorded against a version, with a date'],
        'ai': [   'Stand concepts generated from brief and floor dimensions',
                  'Venue regulations summarised in plain English per show',
                  'Reusable stand elements suggested from previous builds',
                  'Post-show lead lists tidied and routed to the client'],
        'results': [   {'k': 'Deadlines', 'v': 'Back-calculated'},
                       {'k': 'Venue rules', 'v': 'Held once, reused'},
                       {'k': 'Sign-off', 'v': 'Versioned and dated'}],
        'quote': '',
        'quoteBy': '',
        'category': 'community',
        'published': True},
    {   'slug': 'mobile-bar',
        'icon': '🍸',
        'industry': 'Mobile Bar & Event Catering',
        'size': 'Owner + casual staff',
        'color': 'orange',
        'tagline': 'Order too little and you run dry at nine. Order too much and it is money sat in a van.',
        'before': [   'Stock guessed from last time',
                      'Staffing worked out the night before',
                      'Licence applications remembered late',
                      'Sale-or-return reconciled by hand',
                      'Menus rewritten per event in Word'],
        'integrated': [   'Stock forecast from headcount, duration and menu',
                          'Staffing suggested from expected service rate',
                          'Licence and permit deadlines tracked per booking',
                          'Van manifest and returns count in one list',
                          'Branded menus generated per event'],
        'ai': [   'Consumption patterns learned from previous events',
                  'Package options visualised for the customer before booking',
                  'Dietary and allergen requirements collected and collated',
                  'Reorder prompts timed to supplier lead times'],
        'results': [   {'k': 'Stock', 'v': 'Forecast, not guessed'},
                       {'k': 'Staffing', 'v': 'From service rate'},
                       {'k': 'Returns', 'v': 'Counted once'}],
        'quote': '',
        'quoteBy': '',
        'category': 'community',
        'published': True},
    {   'slug': 'film-production-services',
        'icon': '🎬',
        'industry': 'Film & TV Production Services',
        'size': 'Producer + rotating crew',
        'color': 'lilac',
        'tagline': 'Call sheets rebuilt every night, unit moves planned in a group chat, releases signed on '
                   'paper.',
        'before': [   'Call sheets rebuilt daily in Word',
                      'Crew availability chased individually',
                      'Location agreements in a filing cabinet',
                      'Kit split across jobs with no clear picture',
                      'Receipts collected in an envelope'],
        'integrated': [   'Call sheets generated from the shooting schedule',
                          'Crew availability and roles held centrally',
                          'Location records with access, parking and permissions',
                          'Kit allocation visible across concurrent shoots',
                          'Spend captured against the job as it happens'],
        'ai': [   'Schedule changes rippled through call sheets automatically',
                  'Location options matched to script requirements',
                  'Daily production reports drafted from what was shot',
                  'Continuity notes searchable in plain English'],
        'results': [   {'k': 'Call sheets', 'v': 'Generated, not retyped'},
                       {'k': 'Locations', 'v': 'Recorded once'},
                       {'k': 'Kit', 'v': 'Visible across shoots'}],
        'quote': '',
        'quoteBy': '',
        'category': 'digital',
        'published': True},
    {   'slug': 'scaffolding-access',
        'icon': '🪜',
        'industry': 'Scaffolding & Access Hire',
        'size': 'Yard + multiple gangs',
        'color': 'yellow',
        'tagline': 'Statutory inspections come round every seven days whether anyone remembers or not.',
        'before': [   'Inspections logged in paper books',
                      'Handover certificates typed up later',
                      'Hire periods tracked on a whiteboard',
                      'Materials counted in and out by memory',
                      'Variations agreed verbally on site'],
        'integrated': [   'Inspection schedule with reminders per structure',
                          'Handover certificates issued from the job record',
                          'Hire periods and off-hire dates tracked automatically',
                          'Materials booked out to a job and reconciled on return',
                          'Variations captured and priced on site'],
        'ai': [   'Photographic inspection records tagged to the structure',
                  'Overdue inspections escalated before the deadline',
                  'Quantities estimated from elevation photographs',
                  'Weekly hire revenue and stock utilisation summarised'],
        'results': [   {'k': 'Inspections', 'v': 'Scheduled and chased'},
                       {'k': 'Off-hire', 'v': 'Tracked automatically'},
                       {'k': 'Certificates', 'v': 'From the job record'}],
        'quote': '',
        'quoteBy': '',
        'category': 'service',
        'published': True},
    {   'slug': 'builder',
        'icon': '🧱',
        'industry': 'Building Contractor',
        'size': 'Owner + subcontractors',
        'color': 'orange',
        'tagline': 'The margin lives in the gap between what was quoted, what was ordered, and what actually '
                   'got built.',
        'before': [   'Estimates built in a spreadsheet each time',
                      'Subbies booked over the phone',
                      'Variations agreed on site, forgotten by invoicing',
                      'Materials ordered ad hoc, over and under',
                      'Stage payments chased by memory'],
        'integrated': [   'One record per project: quote, orders, labour, variations',
                          'Stage payments raised automatically at each milestone',
                          'Subcontractor schedule and day rates in one place',
                          "Variations logged and priced the moment they're agreed",
                          'Snagging list the client can see and sign off'],
        'ai': [   'Estimates drafted from a priced library that learns from finished jobs',
                  'Material take-offs suggested from the spec',
                  'Progress updates written for the client from site photos',
                  'The weekly what-earned-what summary in plain English'],
        'results': [   {'k': 'Variations', 'v': 'Never lost'},
                       {'k': 'Stage payments', 'v': 'Raised on milestone'},
                       {'k': 'Pricing', 'v': 'Learns from real jobs'}],
        'quote': '',
        'quoteBy': '',
        'category': 'service',
        'published': True},
    {   'slug': 'electrician-renewables',
        'icon': '⚡',
        'industry': 'Electrician / Solar & EV Installer',
        'size': 'Owner + a few installers',
        'color': 'yellow',
        'tagline': 'Every install is a certificate, a warranty, a notification and a compliance deadline — '
                   'filed four different places.',
        'before': [   'Certificates written on site, typed up later',
                      'Notifications to the scheme done manually',
                      'Warranty registrations forgotten',
                      'Quotes for solar/EV built by hand each time',
                      'Aftercare and servicing never followed up'],
        'integrated': [   'Certificates issued from the job, filed against the customer',
                          'Scheme notifications and warranties tracked to completion',
                          'Solar/EV quotes built from a rate card, with payback shown',
                          'Every install a record: panels, inverter, serials, photos',
                          'Service and check-up reminders that resurface as work'],
        'ai': [   "Quote drafted from the customer's usage and roof/parking details",
                  'Compliance paperwork pre-filled from the job record',
                  'Fault-callout notes dictated in the van, written up clean',
                  'Aftercare messages timed to each install'],
        'results': [   {'k': 'Certificates', 'v': 'From the job, filed'},
                       {'k': 'Compliance', 'v': 'Tracked to done'},
                       {'k': 'Servicing', 'v': 'Resurfaces as work'}],
        'quote': '',
        'quoteBy': '',
        'category': 'service',
        'published': True},
    {   'slug': 'cleaning-company',
        'icon': '🧽',
        'industry': 'Cleaning Company',
        'size': 'Owner + mobile teams',
        'color': 'mint',
        'tagline': "Rounds, keys, and cover — a business run entirely on who's where and who's off sick "
                   'today.',
        'before': [   'Rounds planned on a paper schedule',
                      'Cover arranged by frantic phone call',
                      'Key handling logged nowhere',
                      'Invoices raised per client by hand',
                      'One-off quotes guessed from a walk-round'],
        'integrated': [   'Live round schedule per cleaner, per day, per key',
                          "Cover suggested from who's free and nearby",
                          'Recurring invoices and direct debits run themselves',
                          'Client portal: schedule, changes, one-off add-ons',
                          'Key register with photo handover and sign-out'],
        'ai': [   'One-off quotes estimated from property type and rooms',
                  'Cover gaps flagged before the morning they happen',
                  'Client check-in messages after each visit, drafted',
                  'Round profitability summarised so pricing stays right'],
        'results': [   {'k': 'Rounds', 'v': 'Live, not paper'},
                       {'k': 'Cover', 'v': 'Suggested, not scrambled'},
                       {'k': 'Billing', 'v': 'Runs itself'}],
        'quote': '',
        'quoteBy': '',
        'category': 'service',
        'published': True},
    {   'slug': 'beauty-aesthetics',
        'icon': '💅',
        'industry': 'Beauty, Nails & Aesthetics',
        'size': 'Solo or small clinic',
        'color': 'pink',
        'tagline': "No-shows on treatment slots hurt, patch tests get forgotten, and every client's history "
                   'lives in a paper book.',
        'before': [   'Bookings by DM at all hours',
                      'No deposit, so no-shows sting',
                      'Patch-test dates remembered by hand',
                      'Client history and photos on paper cards',
                      'Aftercare given verbally, then forgotten'],
        'integrated': [   'Online booking with a deposit on the slots that hurt to lose',
                          'Patch-test and consent tracked and enforced before booking',
                          'Client record: history, allergies, before/after photos',
                          'Aftercare sent automatically, matched to the treatment',
                          "Rebooking prompts timed to each treatment's cycle"],
        'ai': [   "The awkward pre-treatment note written in the clinic's tone",
                  'Rebooking nudges timed to when it actually wears off',
                  'Consent and medical questions collected before arrival',
                  'Retail aftercare suggested from what was actually done'],
        'results': [   {'k': 'Deposits', 'v': 'On the risky slots'},
                       {'k': 'Patch tests', 'v': 'Enforced, not hoped'},
                       {'k': 'Records', 'v': 'Clinic-owned'}],
        'quote': '',
        'quoteBy': '',
        'category': 'retail',
        'published': True},
    {   'slug': 'butcher-farmshop',
        'icon': '🥩',
        'industry': 'Butcher, Deli & Farm Shop',
        'size': 'Counter + a few staff',
        'color': 'orange',
        'tagline': 'Christmas orders on a paper pad, specials on a chalkboard, and the best customers known '
                   'only by face.',
        'before': [   'Orders taken on a paper pad',
                      'Pre-orders for peak reconciled by hand',
                      'No customer list beyond memory',
                      'Specials written on a board, nowhere online',
                      'Local delivery arranged by phone'],
        'integrated': [   'Online order-ahead and click-and-collect',
                          'Peak pre-orders (Christmas, BBQ season) managed in one list',
                          "Customer list that's theirs, by name and by order",
                          'Specials and cuts posted to site and social in one go',
                          'Local delivery rounds planned and paid online'],
        'ai': [   "Recipe and cut suggestions generated for the week's specials",
                  'Pre-order demand estimated from previous peaks',
                  'Review and reorder prompts to regulars, drafted',
                  "Supplier order lists suggested from what's selling"],
        'results': [   {'k': 'Pre-orders', 'v': 'One list, not a pad'},
                       {'k': 'Customer list', 'v': 'Theirs, by name'},
                       {'k': 'Collection', 'v': 'Booked online'}],
        'quote': '',
        'quoteBy': '',
        'category': 'retail',
        'published': True},
    {   'slug': 'optician',
        'icon': '👓',
        'industry': 'Independent Optician / Audiology',
        'size': 'Practice + small team',
        'color': 'blue',
        'tagline': "The whole business runs on recalls — and a recall that doesn't go out is a test that "
                   'never gets booked.',
        'before': [   'Recalls sent by post, if at all',
                      'Bookings by phone only',
                      'Prescriptions and records on separate systems',
                      'Warranty and repair tracking on paper',
                      'Frames and stock counted by hand'],
        'integrated': [   "Recall engine that knows who's due and nudges them",
                          'Online booking for eye tests and fittings',
                          'One record: prescriptions, history, warranties, repairs',
                          'Repair and remake status the customer can track',
                          'Stock and frame range managed in one place'],
        'ai': [   'Recall messages timed and phrased per patient',
                  'Pre-appointment questions collected before arrival',
                  'Aftercare and adaptation check-ins drafted',
                  'Reorder prompts for contact lens subscriptions'],
        'results': [   {'k': 'Recalls', 'v': 'Never missed'},
                       {'k': 'Bookings', 'v': 'Without a call'},
                       {'k': 'Records', 'v': 'One place'}],
        'quote': '',
        'quoteBy': '',
        'category': 'health',
        'published': True},
    {   'slug': 'nursery-childcare',
        'icon': '🧸',
        'industry': 'Nursery & Childcare',
        'size': 'Setting + staff team',
        'color': 'mint',
        'tagline': 'Ratios, funded hours and daily updates — a regulated business run on paper registers and '
                   'parent goodwill.',
        'before': [   'Daily updates written on paper, sent home',
                      'Funded-hours paperwork done by hand',
                      'Registers and ratios checked manually',
                      'Fees invoiced and chased individually',
                      'Waiting list kept in a notebook'],
        'integrated': [   'Daily update per child parents actually wait for',
                          'Funded-hours and fee splits calculated automatically',
                          'Digital registers with live ratio checks',
                          'Fees, direct debits and extras billed in one place',
                          'Waiting list and enquiries managed, not forgotten'],
        'ai': [   "Daily updates drafted from the day's activities and photos",
                  'Ratio and staffing gaps flagged before they happen',
                  "Funding and fee questions answered from the setting's own policy",
                  "Newsletter and parent comms drafted in the setting's voice"],
        'results': [   {'k': 'Daily updates', 'v': 'Parents wait for them'},
                       {'k': 'Ratios', 'v': 'Checked live'},
                       {'k': 'Funding', 'v': 'Calculated, not fiddled'}],
        'quote': '',
        'quoteBy': '',
        'category': 'education',
        'published': True},
    {   'slug': 'recruitment-agency',
        'icon': '🧑\u200d💼',
        'industry': 'Recruitment Agency',
        'size': 'Consultant-led · small team',
        'color': 'lilac',
        'tagline': 'Candidates in one tool, clients in another, and the whole business paying per seat to '
                   'rent both.',
        'before': [   'Candidate CRM rented per seat',
                      'Client CRM in a second rented tool',
                      'CVs formatted by hand for each role',
                      'Interviews and feedback chased over email',
                      'Placements and invoices tracked in a spreadsheet'],
        'integrated': [   'Candidates and clients in one owned system',
                          'Roles, submissions and stages on one pipeline board',
                          'Branded CV formatting generated in a click',
                          'Interview scheduling and feedback in one thread',
                          'Placements, invoices and margins tracked automatically'],
        'ai': [   'Candidate-to-role matching from skills and history',
                  "CVs reformatted to the agency's template automatically",
                  'Screening call notes turned into a submission summary',
                  'Client and candidate follow-ups drafted on time'],
        'results': [   {'k': 'One system', 'v': 'Not two rented ones'},
                       {'k': 'CV formatting', 'v': 'One click'},
                       {'k': 'Per-seat fees', 'v': 'None'}],
        'quote': '',
        'quoteBy': '',
        'category': 'pro',
        'published': True},
    {   'slug': 'travel-agent',
        'icon': '✈️',
        'industry': 'Travel Agent & Tour Operator',
        'size': 'Independent · small team',
        'color': 'blue',
        'tagline': 'Every trip is a hundred moving parts across a dozen suppliers, held together by email '
                   'and a good memory.',
        'before': [   'Itineraries built in Word per client',
                      'Supplier bookings tracked in an inbox',
                      'Deposits and balances chased by hand',
                      'Documents sent as scattered attachments',
                      'ATOL and insurance paperwork done manually'],
        'integrated': [   'Branded itineraries built from a reusable library',
                          'Supplier bookings and deadlines in one trip record',
                          'Deposit and balance schedule billed automatically',
                          'One client portal: itinerary, documents, payments',
                          'Compliance and insurance tracked per booking'],
        'ai': [   "Draft itineraries generated from the client's brief and budget",
                  'Supplier chase and reconfirm messages drafted on schedule',
                  'Destination guides and packing lists produced per trip',
                  'Post-trip review and rebooking prompts drafted'],
        'results': [   {'k': 'Itineraries', 'v': 'From a library'},
                       {'k': 'Balances', 'v': 'Billed automatically'},
                       {'k': 'One portal', 'v': 'Not scattered email'}],
        'quote': '',
        'quoteBy': '',
        'category': 'community',
        'published': True},
    {   'slug': 'gym-studio',
        'icon': '🏋️',
        'industry': 'Gym & Fitness Studio',
        'size': 'Studio + instructors',
        'color': 'mint',
        'tagline': 'Memberships on one platform, class booking on another, and churn nobody sees coming '
                   "until they've gone.",
        'before': [   'Membership billing on a rented platform',
                      'Class booking in a separate app',
                      'Attendance tracked loosely',
                      'At-risk members noticed only once they cancel',
                      'Class timetable updated in three places'],
        'integrated': [   'Memberships and class booking in one owned system',
                          'Timetable that updates everywhere at once',
                          'Attendance and usage visible per member',
                          'At-risk members surfaced before they quit',
                          'Waitlists, credits and freezes handled automatically'],
        'ai': [   'Members drifting away flagged from attendance patterns',
                  'Win-back and check-in messages drafted at the right moment',
                  'Class demand and timetable suggestions from real usage',
                  'Progress and milestone nudges to keep members coming'],
        'results': [   {'k': 'One system', 'v': 'Not two platforms'},
                       {'k': 'Churn', 'v': 'Caught early'},
                       {'k': 'Timetable', 'v': 'Updates everywhere'}],
        'quote': '',
        'quoteBy': '',
        'category': 'health',
        'published': True}]


async def upsert(e):
    now = datetime.now(timezone.utc).isoformat()
    existing = await db.examples.find_one({"slug": e["slug"]}, {"_id": 0})
    if existing:
        patch = dict(e); patch["updated_at"] = now; patch.pop("order", None)
        await db.examples.update_one({"slug": e["slug"]}, {"$set": patch})
        return f"UPDATE {e['slug']}"
    doc = dict(e); doc["id"] = str(uuid.uuid4())
    doc["created_at"] = now; doc["updated_at"] = now
    if "order" not in doc:
        top = await db.examples.find_one(sort=[("order", -1)], projection={"order": 1})
        doc["order"] = (top or {}).get("order", 0) + 1
    await db.examples.insert_one(doc)
    return f"INSERT {e['slug']}"


async def main():
    print(f"Examples before: {await db.examples.count_documents({})}")
    for e in EXAMPLES:
        print("  " + await upsert(e))
    print(f"Examples after:  {await db.examples.count_documents({})}")
    print("Done.")


if __name__ == "__main__":
    asyncio.run(main())
