// Examples of digital ecosystems built for different kinds of business.
// Demystifies "digital ecosystem" by showing real (illustrative) builds.

export const examples = [
  {
    id: "cafe",
    icon: "☕",
    industry: "Local Café & Brunch Spot",
    size: "1 location · 8 staff",
    color: "yellow",
    tagline: "From a Squarespace site, a Google Sheet roster and a tray of paper receipts — to one branded HQ.",
    before: [
      "Squarespace site for menu",
      "Google Forms for catering",
      "Square POS, takings in a sheet",
      "WhatsApp group for shifts",
      "Paper supplier orders",
    ],
    integrated: [
      "New site with online ordering & booking",
      "Pickup/delivery via Stripe",
      "Staff app for shifts, holidays, tips",
      "Supplier ordering — one button per supplier",
      "Live takings + costs dashboard for the owner",
    ],
    ai: [
      "AI receptionist that handles bookings & FAQs over WhatsApp",
      "Auto-replies to Google reviews in their voice (with owner approval)",
      "Weekly menu performance summary in plain English",
      "Smart inventory: suggests reorders before you run out",
    ],
    quote:
      "I used to spend Sundays catching up on emails, the till and shift swaps. Now it's all in one place — I get my weekends back.",
    quoteBy: "Owner · brunch spot, Bristol",
    results: [
      { k: "Owner time saved", v: "~8 hrs/wk" },
      { k: "Bookings handled by AI", v: "62%" },
      { k: "Review reply time", v: "<10 min" },
    ],
  },
  {
    id: "dental",
    icon: "🦷",
    industry: "Private Dental Clinic",
    size: "2 locations · 18 staff",
    color: "blue",
    tagline: "Replaced 6 tools (booking, reminders, files, intake, payments, comms) with one calm patient portal.",
    before: [
      "Dentally for records (good, kept it)",
      "Calendly for bookings",
      "Mailchimp for newsletters",
      "WhatsApp for reminders (manual)",
      "PDF intake forms via email",
      "Stripe links sent manually",
    ],
    integrated: [
      "Branded patient portal with login",
      "Online booking + smart reminders (email & SMS)",
      "Digital intake forms with allergy/history checks",
      "Treatment plans + estimates with one-click payment",
      "Post-visit care instructions auto-sent",
      "GDPR-safe document vault",
    ],
    ai: [
      "Pre-appointment AI that answers nervous patient questions 24/7",
      "Auto-summary of intake forms — surfacing risks to the dentist",
      "Recall AI: gently nudges patients due for check-ups in their preferred channel",
      "Internal 'ask the SOP' agent for the front desk team",
    ],
    quote:
      "Front desk has stopped drowning. Patients arrive prepared. We've recovered 30+ hours a month between two practices.",
    quoteBy: "Practice manager · dental group, Manchester",
    results: [
      { k: "No-show rate", v: "−47%" },
      { k: "Admin hours saved", v: "30+/mo" },
      { k: "Recall conversions", v: "+38%" },
    ],
  },
  {
    id: "trades",
    icon: "🔧",
    industry: "Plumbing / Electrical Trades",
    size: "Owner + 4 engineers",
    color: "mint",
    tagline: "Job sheets on WhatsApp, quotes in a notebook, customers chasing for updates. Not anymore.",
    before: [
      "Quotes scribbled, sent later",
      "Jobs assigned via WhatsApp",
      "Invoicing via QuickBooks, manually",
      "Customer calls for ETAs all day",
      "Lost time to admin every evening",
    ],
    integrated: [
      "Branded customer site with instant quote estimator",
      "Mobile field-app for engineers — jobs, photos, signatures",
      "Auto SMS to customer when engineer is on the way",
      "Quote → job → invoice → payment, all linked",
      "Live dashboard for the owner (jobs today, revenue, parts)",
    ],
    ai: [
      "AI quote drafter: customer describes the problem, gets a sensible estimate range",
      "AI dispatcher: suggests which engineer + when, factoring travel & skill",
      "Voice-to-job-note: engineer talks, AI fills the job sheet",
      "Review request flows triggered automatically after a job completes",
    ],
    quote:
      "I stopped doing paperwork at 9pm. Quotes go out the same hour. Customers think we've doubled in size.",
    quoteBy: "Owner · plumbing co., Leeds",
    results: [
      { k: "Quotes out same-day", v: "98%" },
      { k: "Avg jobs/engineer", v: "+22%" },
      { k: "5★ reviews", v: "3× more" },
    ],
  },
  {
    id: "coach",
    icon: "🎯",
    industry: "Online Course & Coaching",
    size: "Solo founder + 2 contractors",
    color: "lilac",
    tagline: "Replaced Kajabi + Teachable + Notion + Calendly + ConvertKit with one branded student portal.",
    before: [
      "Kajabi for course (expensive)",
      "Notion for resources",
      "Calendly for 1-1s",
      "ConvertKit for emails",
      "Discord for community",
    ],
    integrated: [
      "Branded student portal with course player",
      "Cohort & 1-1 booking inside the portal",
      "Email automations + payment links built-in",
      "Community space (replaces Discord)",
      "Affiliate / referral tracking",
    ],
    ai: [
      "An AI coach trained on the founder's frameworks — students ask anytime",
      "Personalised next-step recommendations after each lesson",
      "Auto-grader for written assignments with detailed feedback",
      "Content multiplier: turns each podcast into 8 short clips + a newsletter",
    ],
    quote:
      "I cancelled £400/mo of SaaS. My students are more active. The AI coach has saved me 10+ DM hours a week.",
    quoteBy: "Founder · business coach",
    results: [
      { k: "SaaS cost saved", v: "£4.8k/yr" },
      { k: "Course completion", v: "+41%" },
      { k: "Coach hours saved", v: "10+/wk" },
    ],
  },
  {
    id: "ecom",
    icon: "🛍️",
    industry: "DTC Fashion Brand",
    size: "Founder + small team",
    color: "pink",
    tagline: "From Shopify + Klaviyo + Gorgias + ManyChat duct-tape — to a unified storefront with AI baked in.",
    before: [
      "Shopify, default theme",
      "Klaviyo flows (some broken)",
      "Gorgias for support",
      "Manual UGC sourcing",
      "Ad creative outsourced (slow)",
    ],
    integrated: [
      "Headless Shopify storefront — fast, editorial, mobile-first",
      "Loyalty & referral built into checkout",
      "Connected reviews, UGC and product Q&A",
      "Inventory + supplier dashboard",
      "Single customer view across site, email, support",
    ],
    ai: [
      "AI product stylist: 'what goes with this?'",
      "Support agent answering 70% of tickets (returns, sizing, shipping)",
      "Ad creative generator using brand-approved templates",
      "Personal subject-line writer for every Klaviyo campaign",
      "Visual search: shoppers upload an image, see closest products",
    ],
    quote:
      "Customer support cost halved. Conversion up 28%. We finally have time to design the next collection.",
    quoteBy: "Founder · DTC fashion",
    results: [
      { k: "Support cost", v: "−50%" },
      { k: "CVR", v: "+28%" },
      { k: "Email revenue", v: "+62%" },
    ],
  },
  {
    id: "fitness",
    icon: "🏋️",
    industry: "Personal Trainer Studio",
    size: "Owner + 6 trainers",
    color: "orange",
    tagline: "Sticky-notes, Trainerize, MyFitnessPal, Insta DMs — into one branded member app.",
    before: [
      "Trainerize for programs",
      "DMs for check-ins",
      "Google Sheet for sessions",
      "PayPal links for invoices",
      "MyFitnessPal logging (chaotic)",
    ],
    integrated: [
      "Branded member app (iOS + Android)",
      "Booking + payments + class passes",
      "Programs with video + form-check uploads",
      "Trainer chat with shared media",
      "Wearables + nutrition sync",
    ],
    ai: [
      "AI form-check: members upload a video, AI flags posture issues",
      "Personalised weekly check-in survey + AI-summarised report to the trainer",
      "Nutrition coach AI tailored to the member's goal & allergens",
      "Auto-generated celebratory milestones (PRs, streaks) for social sharing",
    ],
    quote:
      "Retention has never been this high. Members say it feels like having a coach in their pocket.",
    quoteBy: "Owner · PT studio, Brighton",
    results: [
      { k: "Member retention", v: "+34%" },
      { k: "Trainer admin", v: "−6 hrs/wk" },
      { k: "Referrals", v: "2× more" },
    ],
  },
];

// Quick categories used for filtering / display on the examples page
export const categories = [
  { id: "all", label: "All examples" },
  { id: "service", label: "Services & trades", ids: ["dental", "trades"] },
  { id: "hospitality", label: "Hospitality", ids: ["cafe"] },
  { id: "digital", label: "Digital & creators", ids: ["coach"] },
  { id: "retail", label: "Retail & e-commerce", ids: ["ecom"] },
  { id: "health", label: "Health & fitness", ids: ["fitness"] },
];
