// Examples of digital ecosystems built for different kinds of business.
// Demystifies "digital ecosystem" by showing real (illustrative) builds.

export const examples = [
  {
    id: "cafe",
    icon: "☕",
    industry: "Local Café & Brunch Spot",
    size: "1 location · 8 staff",
    color: "yellow",
    tagline: "From a Squarespace site, a Google Sheet roster and a tray of paper receipts — to one branded HQ.",
    before: [
      "Squarespace site for menu",
      "Google Forms for catering",
      "Square POS, takings in a sheet",
      "WhatsApp group for shifts",
      "Paper supplier orders",
    ],
    integrated: [
      "New site with online ordering & booking",
      "Pickup/delivery via Stripe",
      "Staff app for shifts, holidays, tips",
      "Supplier ordering — one button per supplier",
      "Live takings + costs dashboard for the owner",
    ],
    ai: [
      "AI receptionist that handles bookings & FAQs over WhatsApp",
      "Auto-replies to Google reviews in their voice (with owner approval)",
      "Weekly menu performance summary in plain English",
      "Smart inventory: suggests reorders before you run out",
    ],
    results: [
      { k: "Owner time saved", v: "Off the owner's plate" },
      { k: "Bookings handled by AI", v: "Handled automatically" },
      { k: "Review reply time", v: "Drafted, ready to send" },
    ],
  },
  {
    id: "dental",
    icon: "🦷",
    industry: "Private Dental Clinic",
    size: "2 locations · 18 staff",
    color: "blue",
    tagline: "Replaced 6 tools (booking, reminders, files, intake, payments, comms) with one calm patient portal.",
    before: [
      "Dentally for records (good, kept it)",
      "Calendly for bookings",
      "Mailchimp for newsletters",
      "WhatsApp for reminders (manual)",
      "PDF intake forms via email",
      "Stripe links sent manually",
    ],
    integrated: [
      "Branded patient portal with login",
      "Online booking + smart reminders (email & SMS)",
      "Digital intake forms with allergy/history checks",
      "Treatment plans + estimates with one-click payment",
      "Post-visit care instructions auto-sent",
      "GDPR-safe document vault",
    ],
    ai: [
      "Pre-appointment AI that answers nervous patient questions 24/7",
      "Auto-summary of intake forms — surfacing risks to the dentist",
      "Recall AI: gently nudges patients due for check-ups in their preferred channel",
      "Internal 'ask the SOP' agent for the front desk team",
    ],
    results: [
      { k: "No-show rate", v: "Smart reminders + deposits" },
      { k: "Admin hours saved", v: "Front desk freed up" },
      { k: "Recall conversions", v: "Recalls chased on their own" },
    ],
  },
  {
    id: "trades",
    icon: "🔧",
    industry: "Plumbing / Electrical Trades",
    size: "Owner + 4 engineers",
    color: "mint",
    tagline: "Job sheets on WhatsApp, quotes in a notebook, customers chasing for updates. Not anymore.",
    before: [
      "Quotes scribbled, sent later",
      "Jobs assigned via WhatsApp",
      "Invoicing via QuickBooks, manually",
      "Customer calls for ETAs all day",
      "Lost time to admin every evening",
    ],
    integrated: [
      "Branded customer site with instant quote estimator",
      "Mobile field-app for engineers — jobs, photos, signatures",
      "Auto SMS to customer when engineer is on the way",
      "Quote → job → invoice → payment, all linked",
      "Live dashboard for the owner (jobs today, revenue, parts)",
    ],
    ai: [
      "AI quote drafter: customer describes the problem, gets a sensible estimate range",
      "AI dispatcher: suggests which engineer + when, factoring travel & skill",
      "Voice-to-job-note: engineer talks, AI fills the job sheet",
      "Review request flows triggered automatically after a job completes",
    ],
    results: [
      { k: "Quotes out same-day", v: "Sent from the van" },
      { k: "Avg jobs/engineer", v: "Less admin per job" },
      { k: "5★ reviews", v: "Requested after every job" },
    ],
  },
  {
    id: "coach",
    icon: "🎯",
    industry: "Online Course & Coaching",
    size: "Solo founder + 2 contractors",
    color: "lilac",
    tagline: "Replaced Kajabi + Teachable + Notion + Calendly + ConvertKit with one branded student portal.",
    before: [
      "Kajabi for course (expensive)",
      "Notion for resources",
      "Calendly for 1-1s",
      "ConvertKit for emails",
      "Discord for community",
    ],
    integrated: [
      "Branded student portal with course player",
      "Cohort & 1-1 booking inside the portal",
      "Email automations + payment links built-in",
      "Community space (replaces Discord)",
      "Affiliate / referral tracking",
    ],
    ai: [
      "An AI coach trained on the founder's frameworks — students ask anytime",
      "Personalised next-step recommendations after each lesson",
      "Auto-grader for written assignments with detailed feedback",
      "Content multiplier: turns each podcast into 8 short clips + a newsletter",
    ],
    results: [
      { k: "SaaS cost saved", v: "Subscriptions replaced" },
      { k: "Course completion", v: "Progress tracked + nudged" },
      { k: "Coach hours saved", v: "Admin automated" },
    ],
  },
  {
    id: "ecom",
    icon: "🛍️",
    industry: "DTC Fashion Brand",
    size: "Founder + small team",
    color: "pink",
    tagline: "From Shopify + Klaviyo + Gorgias + ManyChat duct-tape — to a unified storefront with AI baked in.",
    before: [
      "Shopify, default theme",
      "Klaviyo flows (some broken)",
      "Gorgias for support",
      "Manual UGC sourcing",
      "Ad creative outsourced (slow)",
    ],
    integrated: [
      "Headless Shopify storefront — fast, editorial, mobile-first",
      "Loyalty & referral built into checkout",
      "Connected reviews, UGC and product Q&A",
      "Inventory + supplier dashboard",
      "Single customer view across site, email, support",
    ],
    ai: [
      "AI product stylist: 'what goes with this?'",
      "Support agent answering 70% of tickets (returns, sizing, shipping)",
      "Ad creative generator using brand-approved templates",
      "Personal subject-line writer for every Klaviyo campaign",
      "Visual search: shoppers upload an image, see closest products",
    ],
    results: [
      { k: "Support cost", v: "AI handles routine queries" },
      { k: "CVR", v: "Faster, clearer checkout" },
      { k: "Email revenue", v: "Automated, owned flows" },
    ],
  },
  {
    id: "fitness",
    icon: "🏋️",
    industry: "Personal Trainer Studio",
    size: "Owner + 6 trainers",
    color: "orange",
    tagline: "Sticky-notes, Trainerize, MyFitnessPal, Insta DMs — into one branded member app.",
    before: [
      "Trainerize for programs",
      "DMs for check-ins",
      "Google Sheet for sessions",
      "PayPal links for invoices",
      "MyFitnessPal logging (chaotic)",
    ],
    integrated: [
      "Branded member app (iOS + Android)",
      "Booking + payments + class passes",
      "Programs with video + form-check uploads",
      "Trainer chat with shared media",
      "Wearables + nutrition sync",
    ],
    ai: [
      "AI form-check: members upload a video, AI flags posture issues",
      "Personalised weekly check-in survey + AI-summarised report to the trainer",
      "Nutrition coach AI tailored to the member's goal & allergens",
      "Auto-generated celebratory milestones (PRs, streaks) for social sharing",
    ],
    results: [
      { k: "Member retention", v: "Progress they can see" },
      { k: "Trainer admin", v: "Plans write themselves" },
      { k: "Referrals", v: "Shareable results" },
    ],
  },
  {
    id: "football",
    icon: "⚽",
    industry: "1-to-1 Football Coach",
    size: "Solo coach · 40+ players",
    color: "mint",
    tagline: "Whiteboard drills, WhatsApp video reviews, payments in PayPal — to a branded coaching platform parents trust.",
    before: [
      "WhatsApp groups for each player",
      "Notes in a notebook",
      "Drill videos lost in iPhone",
      "Bank transfers, chased manually",
      "Match-day clashes with the calendar",
    ],
    integrated: [
      "Player & parent portal with login",
      "Session bookings + payments (block bookings, rescheduling)",
      "Drill & technique video library, tagged by skill",
      "Session reports auto-shared with parents",
      "Match calendar with availability + RSVP",
    ],
    ai: [
      "AI video analysis: upload match clip → tagged moments (shots, passes, defensive errors)",
      "Personalised drill plan per player based on their game footage",
      "Parent-friendly progress reports auto-written from session notes",
      "Smart scheduling AI that solves clashes across 40+ players",
      "Voice-to-note: coach speaks after a session, AI writes the report",
    ],
    results: [
      { k: "Admin hours", v: "Reports from a voice note" },
      { k: "Payment chasing", v: "Automated away" },
      { k: "Players (capacity)", v: "Limited by time, not admin" },
    ],
  },
  {
    id: "etsy",
    icon: "🧵",
    industry: "Etsy Maker & Designer",
    size: "Solo · 800 listings",
    color: "pink",
    tagline: "Canva, Midjourney, Etsy ads, Pinterest — endless tabs and burnt creative hours. Now a branded creator HQ.",
    before: [
      "Canva for product mockups (slow)",
      "Midjourney for design ideas (£100s wasted on bad prompts)",
      "Spreadsheet of keywords",
      "Etsy ads guessed at",
      "Pinterest pinned manually",
    ],
    integrated: [
      "Own Shopify-style storefront (own customer data)",
      "Branded creator dashboard: listings, sales, costs",
      "Inventory + variant management",
      "Bulk listing tool (Etsy + own site + Pinterest at once)",
      "Customer support inbox (Etsy convos + email + Insta DMs unified)",
    ],
    ai: [
      "Branded design-prompt app: type a phrase → on-brand product mockup, first try",
      "Etsy SEO assistant: paste a listing → keywords, title, tags, alt text — optimised",
      "Ad creative generator using your brand colours + winning angles",
      "Pinterest pin writer + scheduler in your voice",
      "AI customer service drafting replies to common questions",
    ],
    results: [
      { k: "Listings / day", v: "Bulk-listed, not one-by-one" },
      { k: "Midjourney spend", v: "Owned prompt tools" },
      { k: "Etsy CTR", v: "Sharper listing copy" },
    ],
  },
  {
    id: "accountant",
    icon: "🧮",
    industry: "Small Accountancy Practice",
    size: "Partner + 5 staff · 250 clients",
    color: "blue",
    tagline: "Email-based client chasing, lost PDFs, deadline panic. Replaced with a calm client portal + AI deadline guardian.",
    before: [
      "Email chains for every client",
      "PDFs scattered across Dropbox / inbox",
      "Spreadsheet of deadlines (often out of date)",
      "Manual data entry from receipts",
      "Annual tax return = panic season",
    ],
    integrated: [
      "Branded client portal — secure document upload, e-sign",
      "Engagement letters & onboarding automated",
      "Stripe direct-debit for monthly fees",
      "Deadline tracker — HMRC / Companies House / VAT",
      "Internal staff dashboard with workload per client",
    ],
    ai: [
      "Receipt & invoice OCR: client snaps a photo → categorised entry in Xero",
      "AI 'first-draft' tax computation reviewer flagging anomalies",
      "Client question bot — answers FAQs (allowable expenses, deadlines, etc.) 24/7 in your firm's tone",
      "AI deadline guardian — chases clients via SMS/email in increasing urgency",
      "Annual report writer that pulls from the client's data",
    ],
    results: [
      { k: "Late filings", v: "The chase runs itself" },
      { k: "Avg client onboarding", v: "One link, no email chain" },
      { k: "Capacity per accountant", v: "No per-seat ceiling" },
    ],
  },
  {
    id: "estate-agent",
    icon: "🏡",
    industry: "Independent Estate Agency",
    size: "2 branches · 12 staff",
    color: "lilac",
    tagline: "Rightmove, Zoopla, three CRMs, 20 spreadsheets of viewings. Unified into one branded property platform.",
    before: [
      "Two different CRMs (sales + lettings)",
      "Excel viewing diaries",
      "WhatsApp for landlord comms",
      "DocuSign for contracts",
      "Property photos lost on agents' phones",
    ],
    integrated: [
      "Branded property portal (with their own AVM tool)",
      "Vendor & landlord login: status updates, offers, feedback",
      "Tenant onboarding: referencing, signing, payments end-to-end",
      "Viewing scheduler with auto-confirmations",
      "Internal CRM tying valuations, offers, conveyancing in one view",
    ],
    ai: [
      "AI valuation explainer: shows the vendor why a property is priced that way, with comparables",
      "Auto-written property descriptions (in your tone) from photos + bullet facts",
      "AI lead qualifier: filters enquiries, books only serious ones into viewings",
      "Feedback summariser: vendor sees themed comments after every viewing",
      "After-viewing follow-up emails personalised per buyer's reactions",
    ],
    results: [
      { k: "Time on market", v: "Priced on evidence" },
      { k: "Listings won", v: "Won on honesty" },
      { k: "Negotiator capacity", v: "Enquiries auto-qualified" },
    ],
  },
  {
    id: "restaurant-chain",
    icon: "🍔",
    industry: "Multi-Location Restaurant Group",
    size: "5 sites · 80 staff",
    color: "orange",
    tagline: "Five tills, five rotas, five inboxes. Now one branded HQ that runs every site.",
    before: [
      "Different POS at each site",
      "Rotas printed and pinned",
      "Stock counted on paper",
      "Marketing run on personal Insta accounts",
      "Customer feedback lost in DMs",
    ],
    integrated: [
      "Unified booking, ordering & loyalty across all sites",
      "Staff app: rotas, swaps, payslips, training",
      "Live KPI dashboard for the founders (covers, GP%, labour)",
      "Supplier ordering with auto-replenishment",
      "Branded review hub pulling Google, TripAdvisor, Open Table",
    ],
    ai: [
      "Demand forecasting per site, per shift, per dish",
      "AI menu engineer suggests price/portion tweaks for margin",
      "Customer feedback summariser: themes per site, per week",
      "AI host chatbot handling reservations & dietaries in 12 languages",
    ],
    results: [
      { k: "Food waste", v: "Forecast from covers" },
      { k: "Repeat covers", v: "Own loyalty, own list" },
      { k: "Manager admin", v: "One screen, not six" },
    ],
  },
  {
    id: "agency",
    icon: "🎨",
    industry: "Branding & Marketing Agency",
    size: "Founder + 8 creatives",
    color: "pink",
    tagline: "Time-sheets in Toggl, briefs in Notion, decks in Keynote. Replaced with a branded studio OS.",
    before: [
      "Toggl + spreadsheets for time",
      "Notion + Drive for briefs",
      "Slack for client comms",
      "Keynote / Figma for decks",
      "Invoices manual in QuickBooks",
    ],
    integrated: [
      "Branded studio OS: clients, briefs, time, files, invoices in one",
      "Client portal — review proofs, approve, comment",
      "Project Kanban tied to invoicing & budgets",
      "Knowledge base / case-study library",
      "Auto SOWs and contract signing",
    ],
    ai: [
      "AI proposal & SOW drafter trained on past wins",
      "Creative brief co-pilot: turns sales notes into a designer-ready brief",
      "On-brand image generator for moodboards & decks",
      "Time auto-tracker via calendar + files (no more manual logging)",
      "AI client-mood radar from email/Slack tone — flags red flags early",
    ],
    results: [
      { k: "Billable hours", v: "Less time on admin" },
      { k: "Proposal turnaround", v: "Drafted in minutes" },
      { k: "Client NPS", v: "Always-visible progress" },
    ],
  },
  {
    id: "gp-clinic",
    icon: "🩺",
    industry: "Private GP Clinic Group",
    size: "3 clinics · 22 staff",
    color: "blue",
    tagline: "Calmer waiting rooms, fewer no-shows, and an AI that triages questions before patients call.",
    before: [
      "Phone-only bookings (long holds)",
      "Reception drowning in repeat questions",
      "Test results posted, lost, re-sent",
      "Recall letters by post",
      "Patient leaflets PDFs on a USB stick",
    ],
    integrated: [
      "Branded patient portal with secure messaging",
      "Online booking & smart triage form",
      "Digital results delivery with explainers",
      "Recall + vaccination reminders",
      "Document vault: histories, scripts, referrals",
    ],
    ai: [
      "AI receptionist that triages symptoms and books appropriately",
      "Auto-summary of patient history before the appointment",
      "Plain-English results explainer (with red flags surfaced)",
      "Multilingual translation for consent & info sheets",
      "Recall AI: nudges patients due for check-ups politely",
    ],
    results: [
      { k: "Hold times", v: "AI handles the phones" },
      { k: "No-shows", v: "Smart reminders" },
      { k: "Recall conversion", v: "Recalls run on their own" },
    ],
  },
  {
    id: "boutique-hotel",
    icon: "🏨",
    industry: "Boutique Hotel / B&B",
    size: "12 rooms · family-run",
    color: "yellow",
    tagline: "Booking.com fees eating margin, repeat questions over email. Now a direct-booking ecosystem with an AI concierge.",
    before: [
      "Booking.com & Airbnb only",
      "Stripe links for extras (manual)",
      "Email back-and-forth for arrival info",
      "Excel housekeeping schedule",
      "Local guide printed once a year",
    ],
    integrated: [
      "Branded direct-booking site (skip OTA fees)",
      "Guest portal: arrival info, extras, upgrades, room service",
      "Housekeeping app with checklists",
      "Live availability + dynamic pricing engine",
      "Local recommendations pulled from staff favourites",
    ],
    ai: [
      "AI concierge: answers guest questions 24/7 (in their language)",
      "Auto-personalised welcome message based on booking source & history",
      "Upsell AI: suggests spa, dinner, taxi at the right moment",
      "Review-response drafter (approve in one tap)",
    ],
    results: [
      { k: "Direct bookings", v: "Off the OTAs" },
      { k: "OTA fees saved", v: "Commission-free direct" },
      { k: "Avg upsell", v: "Upsells at booking" },
    ],
  },
  {
    id: "driving-school",
    icon: "🚗",
    industry: "Driving Instructor / School",
    size: "Owner + 6 instructors",
    color: "mint",
    tagline: "Wall planner, cash payments, students texting at 11pm. Now a branded booking + progress app.",
    before: [
      "Wall planner in the kitchen",
      "Texts for booking & cancellations",
      "Cash + bank transfers",
      "Skills tracked in a notebook",
      "Theory tests on paper",
    ],
    integrated: [
      "Branded student app with bookings, payments, lesson recap",
      "Block-booking with discounts",
      "Skill tracker (manoeuvres, mock test, etc.)",
      "Instructor scheduling + pay calc",
      "Theory practice mini-tests",
    ],
    ai: [
      "AI mock-test coach: explains why each answer is right/wrong",
      "Lesson-debrief generator from instructor voice notes",
      "Pass-prep planner: tells the student what to focus on this week",
      "WhatsApp AI handles 'can I book Tuesday?' bookings",
    ],
    results: [
      { k: "Pass rate (first try)", v: "Readiness, evidenced" },
      { k: "Lessons booked online", v: "Booked without a call" },
      { k: "Admin hours", v: "Recaps from a voice note" },
    ],
  },
  {
    id: "tutor",
    icon: "📚",
    industry: "Tutoring / Education Business",
    size: "Founder + 14 tutors",
    color: "lilac",
    tagline: "Tutors found on Wyzant + Superprof, parents emailing for updates. Now a branded learning platform.",
    before: [
      "Tutors paid through Stripe Connect",
      "Parents emailing for progress",
      "Notes in tutors' own Google Docs",
      "WhatsApp for scheduling",
      "Reports written by hand",
    ],
    integrated: [
      "Branded student & parent portal",
      "Lesson booking + payments",
      "Tutor app with prep notes, materials, homework",
      "Parent progress dashboard",
      "Marketplace for in-house exam prep packs",
    ],
    ai: [
      "AI homework grader & explainer (per subject)",
      "Tutor co-pilot: drafts lesson plans + practice questions tailored to the student",
      "Parent-friendly progress report writer (auto from lesson notes)",
      "Matchmaker: pairs new students with the right tutor based on style",
    ],
    results: [
      { k: "Tutor capacity", v: "Admin automated" },
      { k: "Parent retention", v: "Progress parents can see" },
      { k: "Avg report time", v: "Reports in minutes" },
    ],
  },
  {
    id: "law-firm",
    icon: "⚖️",
    industry: "Independent Law Firm",
    size: "3 partners · 9 staff",
    color: "ink",
    tagline: "Word docs, paper signatures, lost emails. Replaced with a calm client portal and AI legal assistant.",
    before: [
      "Outlook + a shared drive",
      "Hard-copy client files",
      "Phone calls for status updates",
      "Manual billing in Xero",
      "Discoveries in 4 different inboxes",
    ],
    integrated: [
      "Branded client portal with case status, documents, invoices",
      "E-signature + ID verification flow",
      "Matter management with automated milestones",
      "Time tracking tied directly to billing",
      "Conflict-check + intake automation",
    ],
    ai: [
      "AI document summariser: 80-page contract → 1-page brief",
      "Drafting co-pilot for standard letters & clauses (firm-approved templates)",
      "Internal 'precedent search' agent across past matters",
      "Client update auto-writer: lawyer voice-notes → polished status email",
      "Compliance flagger for AML / KYC patterns",
    ],
    results: [
      { k: "Drafting time", v: "Drafted from templates" },
      { k: "Matters per fee-earner", v: "Less time on admin" },
      { k: "Client satisfaction", v: "Always-visible progress" },
    ],
  },
  {
    id: "vet",
    icon: "🐕",
    industry: "Vet Clinic / Pet Care",
    size: "1 clinic · 9 staff",
    color: "mint",
    tagline: "Worried owners calling at 6am. Now an AI-assisted pet portal that calms the chaos.",
    before: [
      "Phone lines jammed in the morning",
      "Reminders for vaccines by post",
      "Owner photos lost in WhatsApp",
      "Repeat prescriptions emailed",
      "Records in a desktop system",
    ],
    integrated: [
      "Branded pet portal — one record per pet",
      "Online booking + smart triage",
      "Reminders for vaccines, flea, worming, check-ups",
      "Repeat-script ordering with delivery",
      "Photo/video upload for pre-consult",
    ],
    ai: [
      "AI triage: helps the owner know if it's urgent, can-wait or watch-and-see",
      "Auto-summary of pet history before the appointment",
      "Diet & weight coach for chronic conditions",
      "AI grief support resource library after end-of-life visits",
    ],
    results: [
      { k: "Phone volume", v: "AI handles routine calls" },
      { k: "Recall uptake", v: "Recalls chased automatically" },
      { k: "Owner NPS", v: "Clear, timely comms" },
    ],
  },
  {
    id: "landscaping",
    icon: "🌱",
    industry: "Garden & Landscaping Co.",
    size: "Owner + 5 staff",
    color: "yellow",
    tagline: "Quoting from photos, weather-juggled jobs, invoices done on Sundays. A field-app changed everything.",
    before: [
      "Site visits to quote anything",
      "Paper job sheets",
      "Weather killed scheduling",
      "Customer photos lost",
      "Invoices done on Sundays",
    ],
    integrated: [
      "Customer photo-upload quoting flow",
      "Job dispatch app with weather-aware scheduling",
      "Before / during / after photo log per job",
      "Auto invoice + payment on job complete",
      "Maintenance contracts on recurring billing",
    ],
    ai: [
      "AI sketch-to-quote: customer uploads garden photo + sketch, AI returns design ideas + cost range",
      "Smart scheduler: shifts jobs around forecast rain",
      "AI plant recommendation tool for clients",
      "Voice-to-quote so the owner quotes while driving",
    ],
    results: [
      { k: "Quote → win rate", v: "Visual quotes" },
      { k: "Weather wasted days", v: "Weather-aware scheduling" },
      { k: "Recurring revenue", v: "Maintenance plans built in" },
    ],
  },
  {
    id: "podcaster",
    icon: "🎤",
    industry: "Podcaster / Content Creator",
    size: "Solo · weekly episodes",
    color: "pink",
    tagline: "One podcast, ten platforms, zero time. Now a content engine that distributes everywhere automatically.",
    before: [
      "Riverside / Squadcast for recording",
      "Descript for editing (slow)",
      "Manual reels in CapCut",
      "Show notes in a Google Doc",
      "Newsletter pasted into Substack",
    ],
    integrated: [
      "Branded podcast site with episode pages + transcripts",
      "Membership tier (Patreon-replaced) on own domain",
      "Newsletter signups + RSS in one place",
      "Sponsorship marketplace inside the dashboard",
      "Listener Q&A inbox + voicemail collector",
    ],
    ai: [
      "Auto chapters, transcripts, show notes, SEO titles",
      "10 reels + 5 quote-cards + 3 tweets per episode (in your voice)",
      "Newsletter draft from each episode (you just polish)",
      "Question summariser for AMA episodes",
      "Listener-matched ad sponsor recommender",
    ],
    results: [
      { k: "Audience growth", v: "Owned audience + site" },
      { k: "Sponsorship rev", v: "Own the sponsor relationship" },
      { k: "Post-prod time", v: "Clips generated automatically" },
    ],
  },
  {
    id: "removals",
    icon: "🚚",
    industry: "Removals / Man-with-Van",
    size: "Owner + 2 vans",
    color: "blue",
    tagline: "Booking via phone, quote on the spot, cash in hand. Replaced with an instant-quote booking app.",
    before: [
      "Phone calls only for bookings",
      "Quote by gut feel",
      "Calendar on the fridge",
      "Receipts on paper",
      "Reviews never asked for",
    ],
    integrated: [
      "Instant online quoting from address + photo of items",
      "Branded booking site with payments + deposits",
      "Driver app with route, photos, signatures",
      "Customer comms (ETA SMS, live tracking)",
      "Review request flow after every job",
    ],
    ai: [
      "AI quote engine: photo → estimated load + travel + crew + price",
      "Voice-to-job-note for drivers between stops",
      "Smart route + load planner",
      "Damage detection from photos before/after",
      "AI driver coach: tips per route based on past delays",
    ],
    results: [
      { k: "Quotes / day", v: "Guided self-quote" },
      { k: "Conversion", v: "Answered before rivals" },
      { k: "5★ reviews", v: "Requested after every job" },
    ],
  },
  {
    id: "wedding-planner",
    icon: "💍",
    industry: "Wedding Planner / Venue",
    size: "Founder + 3 planners",
    color: "lilac",
    tagline: "Endless Pinterest boards, vendor emails, spreadsheet budgets. One calm planning portal per couple.",
    before: [
      "Pinterest moodboards shared by link",
      "Vendor coordination over email",
      "Budget spreadsheet (always out of date)",
      "Timeline in Word",
      "Guest list in Excel",
    ],
    integrated: [
      "Couple's portal: moodboard, vendors, budget, timeline, RSVPs",
      "Vendor marketplace + booking inside",
      "Real-time budget tracker connected to invoices",
      "Guest RSVP & dietary tracking",
      "Day-of timeline shared with all suppliers",
    ],
    ai: [
      "Moodboard-to-vendor recommender (style + budget match)",
      "AI script-writer for speeches, vows, MC intros (private to couple)",
      "Smart budget warning AI: flags overspend early",
      "Auto follow-up with vendors stuck on confirmations",
    ],
    results: [
      { k: "Weddings / yr", v: "Less coordination overhead" },
      { k: "Vendor coord time", v: "One shared timeline" },
      { k: "Couple NPS", v: "Everything in one place" },
    ],
  },
  {
    id: "salon",
    icon: "💇",
    industry: "Hair Salon / Barber Chain",
    size: "4 sites · 26 stylists",
    color: "orange",
    tagline: "Bookings on phone, products sold on paper, no idea who's loyal. Now a branded loyalty + booking app.",
    before: [
      "Phone bookings (missed at busy times)",
      "Product sales on paper",
      "No-show texts manual",
      "Loyalty cards (paper, often lost)",
      "Marketing on personal Insta",
    ],
    integrated: [
      "Branded booking app with rebooking + waitlist",
      "Product retail tied to client history",
      "Stylist app: schedule, tips, client preferences",
      "Loyalty points + birthday rewards",
      "Branded reels & content kits per stylist",
    ],
    ai: [
      "AI rebooking nudges based on previous interval",
      "Hair/colour mood-board generator from a client photo",
      "Demand forecasting for retail stock",
      "Personalised aftercare AI message after every visit",
    ],
    results: [
      { k: "Rebooking rate", v: "Rebooking at the chair" },
      { k: "Retail revenue", v: "Aftercare sells itself" },
      { k: "Stylist retention", v: "Records stay with the salon" },
    ],
  },
  {
    id: "cycling-club",
    icon: "🚴",
    industry: "Cycling Club / Sports Community",
    size: "Volunteer-run · 400 members",
    color: "mint",
    tagline: "Strava, Facebook events, WhatsApp groups, paper sign-ups. Replaced with one community platform.",
    before: [
      "Facebook events for rides",
      "WhatsApp for ride leaders",
      "Strava for tracking",
      "Spreadsheet for membership fees",
      "Volunteer rotas on paper",
    ],
    integrated: [
      "Branded community portal & app",
      "Ride calendar with grading + RSVPs",
      "Membership payments & renewals",
      "Routes library with maps & GPX downloads",
      "Volunteer rota & comms",
    ],
    ai: [
      "AI ride-buddy matcher (pace, route, availability)",
      "Auto-summary of every ride for socials (distance, climbing, photo)",
      "Route suggester from preferences & weather",
      "Newsletter writer from ride reports",
    ],
    results: [
      { k: "New members", v: "Easy join + pay" },
      { k: "Ride participation", v: "One place for everything" },
      { k: "Volunteer admin", v: "Automated away" },
    ],
  },,
  {
    id: "event-production",
    icon: "🎪",
    industry: "Event Production & Experiential",
    size: "Office team + freelance crew",
    color: "pink",
    tagline: "Quotes re-typed into job sheets, into WhatsApp, into stock orders. Five copies of the truth, and only some get updated.",
    before: [
      "Concept images made by hand per pitch",
      "Job details re-typed at every stage",
      "Crew briefed in a WhatsApp thread that scrolls",
      "Kit clashes found on load-out day",
      "Stock ordered when someone remembers",
    ],
    integrated: [
      "Approve a quote and the job pack builds itself",
      "Order-by dates worked backwards from load-out",
      "Kit committed elsewhere flagged the moment it clashes",
      "Crew brief at a link: role, call time, site access",
      "Venue library: bay hours, lift sizes, parking, permits",
    ],
    ai: [
      "Concept visuals generated from the client brief, before samples",
      "Stock volumes estimated from the accepted spec",
      "Site issues photographed and routed to the right person",
      "Post-event debrief written from what actually happened",
    ],
    results: [
      { k: "Source of truth", v: "The quote" },
      { k: "Ordering", v: "Backwards from load-out" },
      { k: "Crew brief", v: "A link, not a thread" },
    ],
  },
  {
    id: "marquee-hire",
    icon: "⛺",
    industry: "Marquee & Event Hire",
    size: "Family firm · seasonal crew",
    color: "mint",
    tagline: "Every booking depends on ground conditions and weather nobody can see yet, and three weddings want the same flooring.",
    before: [
      "Availability held in a wall planner",
      "Site visits for every enquiry",
      "Weather contingency agreed by phone",
      "Furniture counts reconciled by hand",
      "Deposits chased manually",
    ],
    integrated: [
      "Live availability by structure, flooring and furniture",
      "Photo-and-measurement site survey from the customer",
      "Weather contingency priced into the quote from the start",
      "Load lists per van, per site, per day",
      "Deposits taken online at booking",
    ],
    ai: [
      "Layout visualised on the customer's own field or garden photo",
      "Capacity and furniture counts from guest numbers",
      "Ground condition risk flagged from forecast and site notes",
      "Off-season enquiry follow-ups drafted automatically",
    ],
    results: [
      { k: "Visualised on", v: "Their own site photo" },
      { k: "Clash detection", v: "Across the season" },
      { k: "Deposits", v: "Taken at booking" },
    ],
  },
  {
    id: "exhibition-stands",
    icon: "🏗️",
    industry: "Exhibition & Stand Builders",
    size: "Studio + build crew",
    color: "blue",
    tagline: "Build and breakdown windows are fixed, fined if missed, and every venue has its own paperwork.",
    before: [
      "Visuals produced per pitch, mostly unpaid",
      "Venue rules re-read from PDFs each time",
      "Health and safety documents emailed late",
      "Shipping deadlines tracked in a spreadsheet",
      "Client sign-off chased over email",
    ],
    integrated: [
      "Client approves visuals and revisions in one place",
      "Venue record holds rules, windows and paperwork",
      "Build and break schedules generated from the show dates",
      "Freight and print deadlines calculated backwards",
      "Sign-off recorded against a version, with a date",
    ],
    ai: [
      "Stand concepts generated from brief and floor dimensions",
      "Venue regulations summarised in plain English per show",
      "Reusable stand elements suggested from previous builds",
      "Post-show lead lists tidied and routed to the client",
    ],
    results: [
      { k: "Deadlines", v: "Back-calculated" },
      { k: "Venue rules", v: "Held once, reused" },
      { k: "Sign-off", v: "Versioned and dated" },
    ],
  },
  {
    id: "mobile-bar",
    icon: "🍸",
    industry: "Mobile Bar & Event Catering",
    size: "Owner + casual staff",
    color: "orange",
    tagline: "Order too little and you run dry at nine. Order too much and it is money sat in a van.",
    before: [
      "Stock guessed from last time",
      "Staffing worked out the night before",
      "Licence applications remembered late",
      "Sale-or-return reconciled by hand",
      "Menus rewritten per event in Word",
    ],
    integrated: [
      "Stock forecast from headcount, duration and menu",
      "Staffing suggested from expected service rate",
      "Licence and permit deadlines tracked per booking",
      "Van manifest and returns count in one list",
      "Branded menus generated per event",
    ],
    ai: [
      "Consumption patterns learned from previous events",
      "Package options visualised for the customer before booking",
      "Dietary and allergen requirements collected and collated",
      "Reorder prompts timed to supplier lead times",
    ],
    results: [
      { k: "Stock", v: "Forecast, not guessed" },
      { k: "Staffing", v: "From service rate" },
      { k: "Returns", v: "Counted once" },
    ],
  },
  {
    id: "film-production-services",
    icon: "🎬",
    industry: "Film & TV Production Services",
    size: "Producer + rotating crew",
    color: "lilac",
    tagline: "Call sheets rebuilt every night, unit moves planned in a group chat, releases signed on paper.",
    before: [
      "Call sheets rebuilt daily in Word",
      "Crew availability chased individually",
      "Location agreements in a filing cabinet",
      "Kit split across jobs with no clear picture",
      "Receipts collected in an envelope",
    ],
    integrated: [
      "Call sheets generated from the shooting schedule",
      "Crew availability and roles held centrally",
      "Location records with access, parking and permissions",
      "Kit allocation visible across concurrent shoots",
      "Spend captured against the job as it happens",
    ],
    ai: [
      "Schedule changes rippled through call sheets automatically",
      "Location options matched to script requirements",
      "Daily production reports drafted from what was shot",
      "Continuity notes searchable in plain English",
    ],
    results: [
      { k: "Call sheets", v: "Generated, not retyped" },
      { k: "Locations", v: "Recorded once" },
      { k: "Kit", v: "Visible across shoots" },
    ],
  },
  {
    id: "scaffolding-access",
    icon: "🪜",
    industry: "Scaffolding & Access Hire",
    size: "Yard + multiple gangs",
    color: "yellow",
    tagline: "Statutory inspections come round every seven days whether anyone remembers or not.",
    before: [
      "Inspections logged in paper books",
      "Handover certificates typed up later",
      "Hire periods tracked on a whiteboard",
      "Materials counted in and out by memory",
      "Variations agreed verbally on site",
    ],
    integrated: [
      "Inspection schedule with reminders per structure",
      "Handover certificates issued from the job record",
      "Hire periods and off-hire dates tracked automatically",
      "Materials booked out to a job and reconciled on return",
      "Variations captured and priced on site",
    ],
    ai: [
      "Photographic inspection records tagged to the structure",
      "Overdue inspections escalated before the deadline",
      "Quantities estimated from elevation photographs",
      "Weekly hire revenue and stock utilisation summarised",
    ],
    results: [
      { k: "Inspections", v: "Scheduled and chased" },
      { k: "Off-hire", v: "Tracked automatically" },
      { k: "Certificates", v: "From the job record" },
    ],
  },
  {
    id: "builder",
    icon: "🧱",
    industry: "Building Contractor",
    size: "Owner + subcontractors",
    color: "orange",
    tagline: "The margin lives in the gap between what was quoted, what was ordered, and what actually got built.",
    before: [
      "Estimates built in a spreadsheet each time",
      "Subbies booked over the phone",
      "Variations agreed on site, forgotten by invoicing",
      "Materials ordered ad hoc, over and under",
      "Stage payments chased by memory",
    ],
    integrated: [
      "One record per project: quote, orders, labour, variations",
      "Stage payments raised automatically at each milestone",
      "Subcontractor schedule and day rates in one place",
      "Variations logged and priced the moment they're agreed",
      "Snagging list the client can see and sign off",
    ],
    ai: [
      "Estimates drafted from a priced library that learns from finished jobs",
      "Material take-offs suggested from the spec",
      "Progress updates written for the client from site photos",
      "The weekly what-earned-what summary in plain English",
    ],
    results: [
      { k: "Variations", v: "Never lost" },
      { k: "Stage payments", v: "Raised on milestone" },
      { k: "Pricing", v: "Learns from real jobs" },
    ],
  },
  {
    id: "electrician-renewables",
    icon: "⚡",
    industry: "Electrician / Solar & EV Installer",
    size: "Owner + a few installers",
    color: "yellow",
    tagline: "Every install is a certificate, a warranty, a notification and a compliance deadline — filed four different places.",
    before: [
      "Certificates written on site, typed up later",
      "Notifications to the scheme done manually",
      "Warranty registrations forgotten",
      "Quotes for solar/EV built by hand each time",
      "Aftercare and servicing never followed up",
    ],
    integrated: [
      "Certificates issued from the job, filed against the customer",
      "Scheme notifications and warranties tracked to completion",
      "Solar/EV quotes built from a rate card, with payback shown",
      "Every install a record: panels, inverter, serials, photos",
      "Service and check-up reminders that resurface as work",
    ],
    ai: [
      "Quote drafted from the customer's usage and roof/parking details",
      "Compliance paperwork pre-filled from the job record",
      "Fault-callout notes dictated in the van, written up clean",
      "Aftercare messages timed to each install",
    ],
    results: [
      { k: "Certificates", v: "From the job, filed" },
      { k: "Compliance", v: "Tracked to done" },
      { k: "Servicing", v: "Resurfaces as work" },
    ],
  },
  {
    id: "cleaning-company",
    icon: "🧽",
    industry: "Cleaning Company",
    size: "Owner + mobile teams",
    color: "mint",
    tagline: "Rounds, keys, and cover — a business run entirely on who's where and who's off sick today.",
    before: [
      "Rounds planned on a paper schedule",
      "Cover arranged by frantic phone call",
      "Key handling logged nowhere",
      "Invoices raised per client by hand",
      "One-off quotes guessed from a walk-round",
    ],
    integrated: [
      "Live round schedule per cleaner, per day, per key",
      "Cover suggested from who's free and nearby",
      "Recurring invoices and direct debits run themselves",
      "Client portal: schedule, changes, one-off add-ons",
      "Key register with photo handover and sign-out",
    ],
    ai: [
      "One-off quotes estimated from property type and rooms",
      "Cover gaps flagged before the morning they happen",
      "Client check-in messages after each visit, drafted",
      "Round profitability summarised so pricing stays right",
    ],
    results: [
      { k: "Rounds", v: "Live, not paper" },
      { k: "Cover", v: "Suggested, not scrambled" },
      { k: "Billing", v: "Runs itself" },
    ],
  },
  {
    id: "beauty-aesthetics",
    icon: "💅",
    industry: "Beauty, Nails & Aesthetics",
    size: "Solo or small clinic",
    color: "pink",
    tagline: "No-shows on treatment slots hurt, patch tests get forgotten, and every client's history lives in a paper book.",
    before: [
      "Bookings by DM at all hours",
      "No deposit, so no-shows sting",
      "Patch-test dates remembered by hand",
      "Client history and photos on paper cards",
      "Aftercare given verbally, then forgotten",
    ],
    integrated: [
      "Online booking with a deposit on the slots that hurt to lose",
      "Patch-test and consent tracked and enforced before booking",
      "Client record: history, allergies, before/after photos",
      "Aftercare sent automatically, matched to the treatment",
      "Rebooking prompts timed to each treatment's cycle",
    ],
    ai: [
      "The awkward pre-treatment note written in the clinic's tone",
      "Rebooking nudges timed to when it actually wears off",
      "Consent and medical questions collected before arrival",
      "Retail aftercare suggested from what was actually done",
    ],
    results: [
      { k: "Deposits", v: "On the risky slots" },
      { k: "Patch tests", v: "Enforced, not hoped" },
      { k: "Records", v: "Clinic-owned" },
    ],
  },
  {
    id: "butcher-farmshop",
    icon: "🥩",
    industry: "Butcher, Deli & Farm Shop",
    size: "Counter + a few staff",
    color: "orange",
    tagline: "Christmas orders on a paper pad, specials on a chalkboard, and the best customers known only by face.",
    before: [
      "Orders taken on a paper pad",
      "Pre-orders for peak reconciled by hand",
      "No customer list beyond memory",
      "Specials written on a board, nowhere online",
      "Local delivery arranged by phone",
    ],
    integrated: [
      "Online order-ahead and click-and-collect",
      "Peak pre-orders (Christmas, BBQ season) managed in one list",
      "Customer list that's theirs, by name and by order",
      "Specials and cuts posted to site and social in one go",
      "Local delivery rounds planned and paid online",
    ],
    ai: [
      "Recipe and cut suggestions generated for the week's specials",
      "Pre-order demand estimated from previous peaks",
      "Review and reorder prompts to regulars, drafted",
      "Supplier order lists suggested from what's selling",
    ],
    results: [
      { k: "Pre-orders", v: "One list, not a pad" },
      { k: "Customer list", v: "Theirs, by name" },
      { k: "Collection", v: "Booked online" },
    ],
  },
  {
    id: "optician",
    icon: "👓",
    industry: "Independent Optician / Audiology",
    size: "Practice + small team",
    color: "blue",
    tagline: "The whole business runs on recalls — and a recall that doesn't go out is a test that never gets booked.",
    before: [
      "Recalls sent by post, if at all",
      "Bookings by phone only",
      "Prescriptions and records on separate systems",
      "Warranty and repair tracking on paper",
      "Frames and stock counted by hand",
    ],
    integrated: [
      "Recall engine that knows who's due and nudges them",
      "Online booking for eye tests and fittings",
      "One record: prescriptions, history, warranties, repairs",
      "Repair and remake status the customer can track",
      "Stock and frame range managed in one place",
    ],
    ai: [
      "Recall messages timed and phrased per patient",
      "Pre-appointment questions collected before arrival",
      "Aftercare and adaptation check-ins drafted",
      "Reorder prompts for contact lens subscriptions",
    ],
    results: [
      { k: "Recalls", v: "Never missed" },
      { k: "Bookings", v: "Without a call" },
      { k: "Records", v: "One place" },
    ],
  },
  {
    id: "nursery-childcare",
    icon: "🧸",
    industry: "Nursery & Childcare",
    size: "Setting + staff team",
    color: "mint",
    tagline: "Ratios, funded hours and daily updates — a regulated business run on paper registers and parent goodwill.",
    before: [
      "Daily updates written on paper, sent home",
      "Funded-hours paperwork done by hand",
      "Registers and ratios checked manually",
      "Fees invoiced and chased individually",
      "Waiting list kept in a notebook",
    ],
    integrated: [
      "Daily update per child parents actually wait for",
      "Funded-hours and fee splits calculated automatically",
      "Digital registers with live ratio checks",
      "Fees, direct debits and extras billed in one place",
      "Waiting list and enquiries managed, not forgotten",
    ],
    ai: [
      "Daily updates drafted from the day's activities and photos",
      "Ratio and staffing gaps flagged before they happen",
      "Funding and fee questions answered from the setting's own policy",
      "Newsletter and parent comms drafted in the setting's voice",
    ],
    results: [
      { k: "Daily updates", v: "Parents wait for them" },
      { k: "Ratios", v: "Checked live" },
      { k: "Funding", v: "Calculated, not fiddled" },
    ],
  },
  {
    id: "recruitment-agency",
    icon: "🧑‍💼",
    industry: "Recruitment Agency",
    size: "Consultant-led · small team",
    color: "lilac",
    tagline: "Candidates in one tool, clients in another, and the whole business paying per seat to rent both.",
    before: [
      "Candidate CRM rented per seat",
      "Client CRM in a second rented tool",
      "CVs formatted by hand for each role",
      "Interviews and feedback chased over email",
      "Placements and invoices tracked in a spreadsheet",
    ],
    integrated: [
      "Candidates and clients in one owned system",
      "Roles, submissions and stages on one pipeline board",
      "Branded CV formatting generated in a click",
      "Interview scheduling and feedback in one thread",
      "Placements, invoices and margins tracked automatically",
    ],
    ai: [
      "Candidate-to-role matching from skills and history",
      "CVs reformatted to the agency's template automatically",
      "Screening call notes turned into a submission summary",
      "Client and candidate follow-ups drafted on time",
    ],
    results: [
      { k: "One system", v: "Not two rented ones" },
      { k: "CV formatting", v: "One click" },
      { k: "Per-seat fees", v: "None" },
    ],
  },
  {
    id: "travel-agent",
    icon: "✈️",
    industry: "Travel Agent & Tour Operator",
    size: "Independent · small team",
    color: "blue",
    tagline: "Every trip is a hundred moving parts across a dozen suppliers, held together by email and a good memory.",
    before: [
      "Itineraries built in Word per client",
      "Supplier bookings tracked in an inbox",
      "Deposits and balances chased by hand",
      "Documents sent as scattered attachments",
      "ATOL and insurance paperwork done manually",
    ],
    integrated: [
      "Branded itineraries built from a reusable library",
      "Supplier bookings and deadlines in one trip record",
      "Deposit and balance schedule billed automatically",
      "One client portal: itinerary, documents, payments",
      "Compliance and insurance tracked per booking",
    ],
    ai: [
      "Draft itineraries generated from the client's brief and budget",
      "Supplier chase and reconfirm messages drafted on schedule",
      "Destination guides and packing lists produced per trip",
      "Post-trip review and rebooking prompts drafted",
    ],
    results: [
      { k: "Itineraries", v: "From a library" },
      { k: "Balances", v: "Billed automatically" },
      { k: "One portal", v: "Not scattered email" },
    ],
  },
  {
    id: "gym-studio",
    icon: "🏋️",
    industry: "Gym & Fitness Studio",
    size: "Studio + instructors",
    color: "mint",
    tagline: "Memberships on one platform, class booking on another, and churn nobody sees coming until they've gone.",
    before: [
      "Membership billing on a rented platform",
      "Class booking in a separate app",
      "Attendance tracked loosely",
      "At-risk members noticed only once they cancel",
      "Class timetable updated in three places",
    ],
    integrated: [
      "Memberships and class booking in one owned system",
      "Timetable that updates everywhere at once",
      "Attendance and usage visible per member",
      "At-risk members surfaced before they quit",
      "Waitlists, credits and freezes handled automatically",
    ],
    ai: [
      "Members drifting away flagged from attendance patterns",
      "Win-back and check-in messages drafted at the right moment",
      "Class demand and timetable suggestions from real usage",
      "Progress and milestone nudges to keep members coming",
    ],
    results: [
      { k: "One system", v: "Not two platforms" },
      { k: "Churn", v: "Caught early" },
      { k: "Timetable", v: "Updates everywhere" },
    ],
  }
];

// Quick categories used for filtering / display on the examples page
export const categories = [
  { id: "all", label: "All" },
  { id: "service", label: "Services & trades", ids: ["trades", "landscaping", "removals", "driving-school", "scaffolding-access", "builder", "electrician-renewables", "cleaning-company" ] },
  { id: "hospitality", label: "Hospitality", ids: ["cafe", "restaurant-chain", "boutique-hotel"] },
  { id: "digital", label: "Digital & creators", ids: ["coach", "etsy", "podcaster", "agency", "film-production-services" ] },
  { id: "retail", label: "Retail & e-commerce", ids: ["ecom", "etsy", "salon", "beauty-aesthetics", "butcher-farmshop" ] },
  { id: "health", label: "Health & fitness", ids: ["fitness", "football", "dental", "gp-clinic", "vet", "optician", "gym-studio" ] },
  { id: "pro", label: "Professional services", ids: ["accountant", "estate-agent", "law-firm", "recruitment-agency" ] },
  { id: "education", label: "Education", ids: ["tutor", "driving-school", "nursery-childcare" ] },
  { id: "community", label: "Community & events", ids: ["wedding-planner", "cycling-club", "event-production", "marquee-hire", "exhibition-stands", "mobile-bar", "travel-agent" ] },
];
