// Examples of digital ecosystems built for different kinds of business.
// Demystifies "digital ecosystem" by showing real (illustrative) builds.

export const examples = [
  {
    id: "cafe",
    icon: "☕",
    industry: "Local Café & Brunch Spot",
    size: "1 location · 8 staff",
    color: "yellow",
    tagline: "From a Squarespace site, a Google Sheet roster and a tray of paper receipts — to one branded HQ.",
    before: [
      "Squarespace site for menu",
      "Google Forms for catering",
      "Square POS, takings in a sheet",
      "WhatsApp group for shifts",
      "Paper supplier orders",
    ],
    integrated: [
      "New site with online ordering & booking",
      "Pickup/delivery via Stripe",
      "Staff app for shifts, holidays, tips",
      "Supplier ordering — one button per supplier",
      "Live takings + costs dashboard for the owner",
    ],
    ai: [
      "AI receptionist that handles bookings & FAQs over WhatsApp",
      "Auto-replies to Google reviews in their voice (with owner approval)",
      "Weekly menu performance summary in plain English",
      "Smart inventory: suggests reorders before you run out",
    ],
    quote:
      "I used to spend Sundays catching up on emails, the till and shift swaps. Now it's all in one place — I get my weekends back.",
    quoteBy: "Owner · brunch spot, Bristol",
    results: [
      { k: "Owner time saved", v: "~8 hrs/wk" },
      { k: "Bookings handled by AI", v: "62%" },
      { k: "Review reply time", v: "<10 min" },
    ],
  },
  {
    id: "dental",
    icon: "🦷",
    industry: "Private Dental Clinic",
    size: "2 locations · 18 staff",
    color: "blue",
    tagline: "Replaced 6 tools (booking, reminders, files, intake, payments, comms) with one calm patient portal.",
    before: [
      "Dentally for records (good, kept it)",
      "Calendly for bookings",
      "Mailchimp for newsletters",
      "WhatsApp for reminders (manual)",
      "PDF intake forms via email",
      "Stripe links sent manually",
    ],
    integrated: [
      "Branded patient portal with login",
      "Online booking + smart reminders (email & SMS)",
      "Digital intake forms with allergy/history checks",
      "Treatment plans + estimates with one-click payment",
      "Post-visit care instructions auto-sent",
      "GDPR-safe document vault",
    ],
    ai: [
      "Pre-appointment AI that answers nervous patient questions 24/7",
      "Auto-summary of intake forms — surfacing risks to the dentist",
      "Recall AI: gently nudges patients due for check-ups in their preferred channel",
      "Internal 'ask the SOP' agent for the front desk team",
    ],
    quote:
      "Front desk has stopped drowning. Patients arrive prepared. We've recovered 30+ hours a month between two practices.",
    quoteBy: "Practice manager · dental group, Manchester",
    results: [
      { k: "No-show rate", v: "−47%" },
      { k: "Admin hours saved", v: "30+/mo" },
      { k: "Recall conversions", v: "+38%" },
    ],
  },
  {
    id: "trades",
    icon: "🔧",
    industry: "Plumbing / Electrical Trades",
    size: "Owner + 4 engineers",
    color: "mint",
    tagline: "Job sheets on WhatsApp, quotes in a notebook, customers chasing for updates. Not anymore.",
    before: [
      "Quotes scribbled, sent later",
      "Jobs assigned via WhatsApp",
      "Invoicing via QuickBooks, manually",
      "Customer calls for ETAs all day",
      "Lost time to admin every evening",
    ],
    integrated: [
      "Branded customer site with instant quote estimator",
      "Mobile field-app for engineers — jobs, photos, signatures",
      "Auto SMS to customer when engineer is on the way",
      "Quote → job → invoice → payment, all linked",
      "Live dashboard for the owner (jobs today, revenue, parts)",
    ],
    ai: [
      "AI quote drafter: customer describes the problem, gets a sensible estimate range",
      "AI dispatcher: suggests which engineer + when, factoring travel & skill",
      "Voice-to-job-note: engineer talks, AI fills the job sheet",
      "Review request flows triggered automatically after a job completes",
    ],
    quote:
      "I stopped doing paperwork at 9pm. Quotes go out the same hour. Customers think we've doubled in size.",
    quoteBy: "Owner · plumbing co., Leeds",
    results: [
      { k: "Quotes out same-day", v: "98%" },
      { k: "Avg jobs/engineer", v: "+22%" },
      { k: "5★ reviews", v: "3× more" },
    ],
  },
  {
    id: "coach",
    icon: "🎯",
    industry: "Online Course & Coaching",
    size: "Solo founder + 2 contractors",
    color: "lilac",
    tagline: "Replaced Kajabi + Teachable + Notion + Calendly + ConvertKit with one branded student portal.",
    before: [
      "Kajabi for course (expensive)",
      "Notion for resources",
      "Calendly for 1-1s",
      "ConvertKit for emails",
      "Discord for community",
    ],
    integrated: [
      "Branded student portal with course player",
      "Cohort & 1-1 booking inside the portal",
      "Email automations + payment links built-in",
      "Community space (replaces Discord)",
      "Affiliate / referral tracking",
    ],
    ai: [
      "An AI coach trained on the founder's frameworks — students ask anytime",
      "Personalised next-step recommendations after each lesson",
      "Auto-grader for written assignments with detailed feedback",
      "Content multiplier: turns each podcast into 8 short clips + a newsletter",
    ],
    quote:
      "I cancelled £400/mo of SaaS. My students are more active. The AI coach has saved me 10+ DM hours a week.",
    quoteBy: "Founder · business coach",
    results: [
      { k: "SaaS cost saved", v: "£4.8k/yr" },
      { k: "Course completion", v: "+41%" },
      { k: "Coach hours saved", v: "10+/wk" },
    ],
  },
  {
    id: "ecom",
    icon: "🛍️",
    industry: "DTC Fashion Brand",
    size: "Founder + small team",
    color: "pink",
    tagline: "From Shopify + Klaviyo + Gorgias + ManyChat duct-tape — to a unified storefront with AI baked in.",
    before: [
      "Shopify, default theme",
      "Klaviyo flows (some broken)",
      "Gorgias for support",
      "Manual UGC sourcing",
      "Ad creative outsourced (slow)",
    ],
    integrated: [
      "Headless Shopify storefront — fast, editorial, mobile-first",
      "Loyalty & referral built into checkout",
      "Connected reviews, UGC and product Q&A",
      "Inventory + supplier dashboard",
      "Single customer view across site, email, support",
    ],
    ai: [
      "AI product stylist: 'what goes with this?'",
      "Support agent answering 70% of tickets (returns, sizing, shipping)",
      "Ad creative generator using brand-approved templates",
      "Personal subject-line writer for every Klaviyo campaign",
      "Visual search: shoppers upload an image, see closest products",
    ],
    quote:
      "Customer support cost halved. Conversion up 28%. We finally have time to design the next collection.",
    quoteBy: "Founder · DTC fashion",
    results: [
      { k: "Support cost", v: "−50%" },
      { k: "CVR", v: "+28%" },
      { k: "Email revenue", v: "+62%" },
    ],
  },
  {
    id: "fitness",
    icon: "🏋️",
    industry: "Personal Trainer Studio",
    size: "Owner + 6 trainers",
    color: "orange",
    tagline: "Sticky-notes, Trainerize, MyFitnessPal, Insta DMs — into one branded member app.",
    before: [
      "Trainerize for programs",
      "DMs for check-ins",
      "Google Sheet for sessions",
      "PayPal links for invoices",
      "MyFitnessPal logging (chaotic)",
    ],
    integrated: [
      "Branded member app (iOS + Android)",
      "Booking + payments + class passes",
      "Programs with video + form-check uploads",
      "Trainer chat with shared media",
      "Wearables + nutrition sync",
    ],
    ai: [
      "AI form-check: members upload a video, AI flags posture issues",
      "Personalised weekly check-in survey + AI-summarised report to the trainer",
      "Nutrition coach AI tailored to the member's goal & allergens",
      "Auto-generated celebratory milestones (PRs, streaks) for social sharing",
    ],
    quote:
      "Retention has never been this high. Members say it feels like having a coach in their pocket.",
    quoteBy: "Owner · PT studio, Brighton",
    results: [
      { k: "Member retention", v: "+34%" },
      { k: "Trainer admin", v: "−6 hrs/wk" },
      { k: "Referrals", v: "2× more" },
    ],
  },
  {
    id: "football",
    icon: "⚽",
    industry: "1-to-1 Football Coach",
    size: "Solo coach · 40+ players",
    color: "mint",
    tagline: "Whiteboard drills, WhatsApp video reviews, payments in PayPal — to a branded coaching platform parents trust.",
    before: [
      "WhatsApp groups for each player",
      "Notes in a notebook",
      "Drill videos lost in iPhone",
      "Bank transfers, chased manually",
      "Match-day clashes with the calendar",
    ],
    integrated: [
      "Player & parent portal with login",
      "Session bookings + payments (block bookings, rescheduling)",
      "Drill & technique video library, tagged by skill",
      "Session reports auto-shared with parents",
      "Match calendar with availability + RSVP",
    ],
    ai: [
      "AI video analysis: upload match clip → tagged moments (shots, passes, defensive errors)",
      "Personalised drill plan per player based on their game footage",
      "Parent-friendly progress reports auto-written from session notes",
      "Smart scheduling AI that solves clashes across 40+ players",
      "Voice-to-note: coach speaks after a session, AI writes the report",
    ],
    quote:
      "Parents see real progress on paper, players love the videos, and I get my Sunday evenings back.",
    quoteBy: "Coach · 1-to-1 football, Surrey",
    results: [
      { k: "Admin hours", v: "−9 hrs/wk" },
      { k: "Payment chasing", v: "Gone" },
      { k: "Players (capacity)", v: "+60%" },
    ],
  },
  {
    id: "etsy",
    icon: "🧵",
    industry: "Etsy Maker & Designer",
    size: "Solo · 800 listings",
    color: "pink",
    tagline: "Canva, Midjourney, Etsy ads, Pinterest — endless tabs and burnt creative hours. Now a branded creator HQ.",
    before: [
      "Canva for product mockups (slow)",
      "Midjourney for design ideas (£100s wasted on bad prompts)",
      "Spreadsheet of keywords",
      "Etsy ads guessed at",
      "Pinterest pinned manually",
    ],
    integrated: [
      "Own Shopify-style storefront (own customer data)",
      "Branded creator dashboard: listings, sales, costs",
      "Inventory + variant management",
      "Bulk listing tool (Etsy + own site + Pinterest at once)",
      "Customer support inbox (Etsy convos + email + Insta DMs unified)",
    ],
    ai: [
      "Branded design-prompt app: type a phrase → on-brand product mockup, first try",
      "Etsy SEO assistant: paste a listing → keywords, title, tags, alt text — optimised",
      "Ad creative generator using your brand colours + winning angles",
      "Pinterest pin writer + scheduler in your voice",
      "AI customer service drafting replies to common questions",
    ],
    quote:
      "I used to spend 3 hours getting one product image right. Now it takes 5 minutes and looks better. The keyword AI alone changed everything.",
    quoteBy: "Maker · home decor on Etsy",
    results: [
      { k: "Listings / day", v: "10× more" },
      { k: "Midjourney spend", v: "−70%" },
      { k: "Etsy CTR", v: "+58%" },
    ],
  },
  {
    id: "accountant",
    icon: "🧮",
    industry: "Small Accountancy Practice",
    size: "Partner + 5 staff · 250 clients",
    color: "blue",
    tagline: "Email-based client chasing, lost PDFs, deadline panic. Replaced with a calm client portal + AI deadline guardian.",
    before: [
      "Email chains for every client",
      "PDFs scattered across Dropbox / inbox",
      "Spreadsheet of deadlines (often out of date)",
      "Manual data entry from receipts",
      "Annual tax return = panic season",
    ],
    integrated: [
      "Branded client portal — secure document upload, e-sign",
      "Engagement letters & onboarding automated",
      "Stripe direct-debit for monthly fees",
      "Deadline tracker — HMRC / Companies House / VAT",
      "Internal staff dashboard with workload per client",
    ],
    ai: [
      "Receipt & invoice OCR: client snaps a photo → categorised entry in Xero",
      "AI 'first-draft' tax computation reviewer flagging anomalies",
      "Client question bot — answers FAQs (allowable expenses, deadlines, etc.) 24/7 in your firm's tone",
      "AI deadline guardian — chases clients via SMS/email in increasing urgency",
      "Annual report writer that pulls from the client's data",
    ],
    quote:
      "Deadline season went from chaos to calm. Clients send receipts in seconds, and the AI catches what my juniors miss.",
    quoteBy: "Managing partner · accountancy firm, Reading",
    results: [
      { k: "Late filings", v: "−92%" },
      { k: "Avg client onboarding", v: "3 days → 1" },
      { k: "Capacity per accountant", v: "+40%" },
    ],
  },
  {
    id: "estate-agent",
    icon: "🏡",
    industry: "Independent Estate Agency",
    size: "2 branches · 12 staff",
    color: "lilac",
    tagline: "Rightmove, Zoopla, three CRMs, 20 spreadsheets of viewings. Unified into one branded property platform.",
    before: [
      "Two different CRMs (sales + lettings)",
      "Excel viewing diaries",
      "WhatsApp for landlord comms",
      "DocuSign for contracts",
      "Property photos lost on agents' phones",
    ],
    integrated: [
      "Branded property portal (with their own AVM tool)",
      "Vendor & landlord login: status updates, offers, feedback",
      "Tenant onboarding: referencing, signing, payments end-to-end",
      "Viewing scheduler with auto-confirmations",
      "Internal CRM tying valuations, offers, conveyancing in one view",
    ],
    ai: [
      "AI valuation explainer: shows the vendor why a property is priced that way, with comparables",
      "Auto-written property descriptions (in your tone) from photos + bullet facts",
      "AI lead qualifier: filters enquiries, books only serious ones into viewings",
      "Feedback summariser: vendor sees themed comments after every viewing",
      "After-viewing follow-up emails personalised per buyer's reactions",
    ],
    quote:
      "Vendors finally feel informed. Junior agents close more because the AI does the chasing.",
    quoteBy: "Director · independent agency, Surrey",
    results: [
      { k: "Time on market", v: "−21%" },
      { k: "Listings won", v: "+47%" },
      { k: "Negotiator capacity", v: "+30%" },
    ],
  },
];

// Quick categories used for filtering / display on the examples page
export const categories = [
  { id: "all", label: "All examples" },
  { id: "service", label: "Services & trades", ids: ["dental", "trades"] },
  { id: "hospitality", label: "Hospitality", ids: ["cafe"] },
  { id: "digital", label: "Digital & creators", ids: ["coach", "etsy"] },
  { id: "retail", label: "Retail & e-commerce", ids: ["ecom", "etsy"] },
  { id: "health", label: "Health & fitness", ids: ["fitness", "football"] },
  { id: "pro", label: "Professional services", ids: ["accountant", "estate-agent"] },
];
